---
releases:
- name: windows-proxy
  version: 0+dev.30

addons:
  - name: windows-proxy-addon
    jobs:
      - name: set-proxy
        release: windows-proxy
        properties:
          set-proxy:
            enabled: true
            proxy-url: http://192.168.1.1:8080
            bypass-list: "*.local;<local>"
    include:
      stemcell:
      - os: windows2012R2
